// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.sparrow.remote.auto;

public final class GrpcService {
  private GrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Metadata_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Metadata_HeadersEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Metadata_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Payload_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022grpc_service.proto\022\005proto\032\031google/prot" +
      "obuf/any.proto\"\211\001\n\010Metadata\022\014\n\004type\030\003 \001(" +
      "\t\022\020\n\010clientIp\030\010 \001(\t\022-\n\007headers\030\007 \003(\0132\034.p" +
      "roto.Metadata.HeadersEntry\032.\n\014HeadersEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"P\n\007Pa" +
      "yload\022!\n\010metadata\030\002 \001(\0132\017.proto.Metadata" +
      "\022\"\n\004body\030\003 \001(\0132\024.google.protobuf.Any26\n\007" +
      "Request\022+\n\007request\022\016.proto.Payload\032\016.pro" +
      "to.Payload\"\0002J\n\017BiRequestStream\0227\n\017reque" +
      "stBiStream\022\016.proto.Payload\032\016.proto.Paylo" +
      "ad\"\000(\0010\001B\033\n\027com.sparrow.remote.autoP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_proto_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Metadata_descriptor,
        new String[] { "Type", "ClientIp", "Headers", });
    internal_static_proto_Metadata_HeadersEntry_descriptor =
      internal_static_proto_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_proto_Metadata_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Metadata_HeadersEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_proto_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Payload_descriptor,
        new String[] { "Metadata", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
