// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.sparrow.remote.auto;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Metadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <code>.proto.Metadata metadata = 2;</code>
   */
  Metadata getMetadata();
  /**
   * <code>.proto.Metadata metadata = 2;</code>
   */
  MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  boolean hasBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  com.google.protobuf.Any getBody();
  /**
   * <code>.google.protobuf.Any body = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
}
